apiVersion: apps/v1
kind: Deployment
namespace: weather-api-namespace
metadata:
  name: weather-api-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - name: weather-api-container
        image: sathishkumar6/apis:weatherapi
        ports:
        - containerPort: 8080

