apiVersion: v1
kind: Service
namespace: weather-api-namespace
metadata:
  name: weather-api-service
spec:
  selector:
    app: weather-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
